# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PySide2 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 650)
        MainWindow.setMinimumSize(QtCore.QSize(650, 650))
        MainWindow.setMaximumSize(QtCore.QSize(650, 650))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        MainWindow.setIconSize(QtCore.QSize(80, 80))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(650, 650))
        self.centralwidget.setMaximumSize(QtCore.QSize(650, 650))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top = QtWidgets.QFrame(self.centralwidget)
        self.Top.setMinimumSize(QtCore.QSize(650, 150))
        self.Top.setMaximumSize(QtCore.QSize(650, 150))
        self.Top.setStyleSheet("background-color: rgba(15, 32, 39, 98);")
        self.Top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top.setLineWidth(0)
        self.Top.setObjectName("Top")
        self.InputSelect = QtWidgets.QComboBox(self.Top)
        self.InputSelect.setGeometry(QtCore.QRect(130, 110, 521, 41))
        self.InputSelect.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.517, stop:0 rgba(15, 32, 39, 98), stop:1 rgba(44, 83, 100, 255));\n"
"color: rgb(87, 255, 191)")
        self.InputSelect.setObjectName("InputSelect")
        self.Input = QtWidgets.QLabel(self.Top)
        self.Input.setGeometry(QtCore.QRect(0, 105, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(24)
        self.Input.setFont(font)
        self.Input.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: rgb(87, 255, 191)")
        self.Input.setAlignment(QtCore.Qt.AlignCenter)
        self.Input.setObjectName("Input")
        self.label = QtWidgets.QLabel(self.Top)
        self.label.setGeometry(QtCore.QRect(0, 5, 651, 101))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(56)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"color: #556270;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.Top)
        self.Main = QtWidgets.QFrame(self.centralwidget)
        self.Main.setMinimumSize(QtCore.QSize(650, 500))
        self.Main.setMaximumSize(QtCore.QSize(650, 500))
        self.Main.setStyleSheet("background-color: rgba(15, 32, 39, 98);")
        self.Main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main.setLineWidth(0)
        self.Main.setObjectName("Main")
        self.Image = QtWidgets.QLabel(self.Main)
        self.Image.setGeometry(QtCore.QRect(0, 5, 651, 351))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.Image.setFont(font)
        self.Image.setStyleSheet("background-color: none;")
        self.Image.setText("")
        self.Image.setObjectName("Image")
        self.label_2 = QtWidgets.QLabel(self.Main)
        self.label_2.setGeometry(QtCore.QRect(-10, 395, 661, 111))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;\n"
"color: blue;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.Main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EmoCh"))
        self.Input.setText(_translate("MainWindow", "Input:"))
        self.label.setText(_translate("MainWindow", "EmoCh"))
        self.label_2.setText(_translate("MainWindow", "Just a sec..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
